### ISSUE TITLE
packing for gentoo

### ISSUE THREAD

**Issue by dm9pZCAq** [kiedtl/huxdemp#1]
hello,

you wrote a very cool program (with interesting source code btw) and i created a package for it in my [overlay](https://notabug.org/dm9pZCAq/dm9pZCAq-overlay)

so if yo planned to include info about installing `huxdemp` in different distros you can include instruction for Gentoo:
```sh
sudo eselect repository enable dm9pZCAq
sudo emerge --sync dm9pZCAq
sudo emerge sys-apps/huxdemp::dm9pZCAq
```

**Comment by kiedtl** [comment]
Thanks! I'll add this to the README when v2 is released.
