### ISSUE TITLE
maybe support for `luajit`?

### ISSUE THREAD

**Issue by dm9pZCAq** [kiedtl/huxdemp#3]
it would be nice if `huxdemp` would support `luajit`

**Comment by kiedtl** [comment]
It would, but I'm not sure it's worth the effort (and resulting code complexity from working around Lua 5.1 incompatibilities). What upsides (other than speed) do you see if huxdemp supported LuaJIT?

**Comment by dm9pZCAq** [comment]
> Lua 5.1 incompatibilities

it looks like `luajit` has some compatibilities with `lua5.2`
https://luajit.org/extensions.html#lua52


> What upsides

i think only speed

**Comment by kiedtl** [comment]
> it looks like luajit has some compatibilities with lua5.2

True, but scripts will still have to adjust for the possibility of `huxdemp` being built with LuaJIT instead of Lua5.2 -- the forwards-compatibility isn't complete. I don't think it's worth the effort for someone who's writing a small one-off script for this utility, unfortunately.
