### ISSUE TITLE
spurious spaced between bytes

### ISSUE THREAD

**Issue by nkh** [kiedtl/huxdemp#7]
depending on the space available, huxd will insert extra spaces between bytes, resulting in lost space that could be used to have more bytes instead

in my case, I have enough place to have 32 bytes but huxd decided to insert spaces which makes everything look a bit worse, left is to show less bytes but 27 bytes is a bit weird

![screenshot_2023-07-20_14-39-14](https://github.com/kiedtl/huxdemp/assets/45409/ef362955-73e9-4c15-a3a0-0b8eb22f3a8b)
![screenshot_2023-07-20_14-38-13](https://github.com/kiedtl/huxdemp/assets/45409/db69b136-154c-4599-ac6e-a067dd6e1ae5)

**Comment by kiedtl** [comment]
I'm unable to reproduce this, it looks like a terminal/font quirk to me. What terminal is this, and how wide was it in each screenshot?

It's very weird, because huxdemp isn't supposed to know or care about the dimensions of the terminal at all...

> left is to show less bytes but 27 bytes is a bit weird

Not sure I understand.

**Comment by nkh** [comment]
Not sure what the terminal or font could have for impact, there's a certain amount of characters in a terminal, that's it. Anyways Konkeror with tmux on top.

I can't answer for sure but as i was testing but I believe it's 133 characters wide as that's the size of my file manager preview and that's where I use huxdemp.

Let me know if I can run any more tests for you.

**Comment by kiedtl** [comment]
I'm unable to produce this, seems to be working as expected for me.

- http://0x0.st/H9vM.gif (Excuse the colorscheme)

> Konkeror

I've never heard of this, I assume you mean Konsole?

What file manager is this? Maybe has something to do with it.

**Comment by nkh** [comment]
Yes I meant Konsole. And it's unrelated to the file manager as it runs in it's own terminal.

I'l try to find time to run more tests and report back.

**Comment by kiedtl** [comment]
May I ask why this was closed? Were you unable to reproduce it?

**Comment by nkh** [comment]
Of course you can :)

As I didn't find time to reproduce it I felt it was better to close it and then reopen it if necessary. 

Some authors close issues as soon as they think it's done not caring about the user testing it, I can only congratulate you for being more thorough.

And since you made this extra effort, the least I can do is to find time today to look at this!

**Comment by nkh** [comment]
Ok, if I may guess ...

huxdemp prints the offset, 4 spaces, 14 byte tuples, 2 spaces, 14 byte tuples, 5 spaces, the ASCII characters, and 4 final spaces

What we see in the screenshots above is simply the terminal wrapping the line which is now too long for the display. I would agree that this is not a problem with Huxdemp but me not giving it enough space. or I could change the -l option based on the screen width.

But ...

Maybe it's worth considering another spacing. What about:
- offset
- 3 spaces, maybe even 2 since it's possible to color the offset differently
- byte tuples
- 2 spaces
- byte tuples
- 3 spaces
- ascii dump
- nothing after

That's 10-11 less characters and may make a difference. But don't do it for me, I'm probably going to use my own hex dumper because it can understand the format of the input. https://github.com/nkh/P5-Data-HexDump-Range

**Comment by kiedtl** [comment]
> What we see in the screenshots above is simply the terminal wrapping the line which is now too long for the display. I would agree that this is not a problem with Huxdemp but me not giving it enough space.

Ok ok, I see. I must admit I'm still confused by the screenshots, that seem to show the first one taking up more space than the second. (Unless the font sizes are different?)

> Maybe it's worth considering another spacing. What about:

That's definitely something I could look into at some point when I have more time to work on huxdemp :) "Compact" mode would certainly be useful.

Anyway. Thank you for working with me here :)
